export const categories = [
    { value: 'Coches', label: 'Coches' },
    { value: 'Coches eléctricos', label: 'Coches eléctricos' },
    { value: 'Motos', label: 'Motos' },
    { value: 'Motor y Accesorios', label: 'Motor y Accesorios' },
    { value: 'Moda y Accesorios', label: 'Moda y Accesorios' },
    { value: 'Inmobiliaria', label: 'Inmobiliaria' },
    { value: 'TV, Audio y Foto', label: 'TV, Audio y Foto' },
    { value: 'Móviles y Telefonía', label: 'Móviles y Telefonía' },
    { value: 'Informática y Electrónica', label: 'Informática y Electrónica' },
    { value: 'Deporte y Ocio', label: 'Deporte y Ocio' },
    { value: 'Bicicletas', label: 'Bicicletas' },
    { value: 'Consolas y Videojuegos', label: 'Consolas y Videojuegos' },
    { value: 'Hogar y Jardín', label: 'Hogar y Jardín' },
    { value: 'Electrodomésticos', label: 'Electrodomésticos' },
    { value: 'Cine, Libros y Música', label: 'Cine, Libros y Música' },
    { value: 'Niños y Bebés', label: 'Niños y Bebés' },
    { value: 'Coleccionismo', label: 'Coleccionismo' },
    { value: 'Construcción y Reformas', label: 'Construcción y Reformas' },
    { value: 'Industria y Agricultura', label: 'Industria y Agricultura' },
    { value: 'Otros', label: 'Otros' },
  ];