"""empty message

Revision ID: 01321acfdcee
Revises: 1fd74d51374b
Create Date: 2023-02-09 09:29:31.858987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01321acfdcee'
down_revision = '1fd74d51374b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
