"""empty message

Revision ID: 102e3a98c1e1
Revises: 4dbab25a6785
Create Date: 2023-02-03 12:26:29.357693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102e3a98c1e1'
down_revision = '4dbab25a6785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Product', 'price',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Product', 'price',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=19, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
