"""empty message

Revision ID: 1e7499454281
Revises: c9015d7a2c7f
Create Date: 2023-03-01 15:37:53.815010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7499454281'
down_revision = 'c9015d7a2c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.NUMERIC(precision=7, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
