"""empty message

Revision ID: 1fd74d51374b
Revises: 
Create Date: 2023-02-09 09:27:23.082101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd74d51374b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('account_prefix', sa.String(length=10), nullable=True),
    sa.Column('account_number', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('paypal', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('hash', sa.String(length=200), nullable=True),
    sa.Column('location_street_number', sa.Integer(), nullable=True),
    sa.Column('location_street_name', sa.String(length=100), nullable=True),
    sa.Column('location_city', sa.String(length=50), nullable=True),
    sa.Column('location_state', sa.String(length=50), nullable=True),
    sa.Column('location_country', sa.String(length=50), nullable=True),
    sa.Column('location_postcode', sa.String(length=50), nullable=True),
    sa.Column('dob_date', sa.String(length=100), nullable=True),
    sa.Column('dob_age', sa.Integer(), nullable=True),
    sa.Column('registered_date', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('picture_large', sa.String(), nullable=True),
    sa.Column('picture_medium', sa.String(), nullable=True),
    sa.Column('picture_thumbnail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('paypal'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('images', sa.String(), nullable=False),
    sa.Column('created_at_product', sa.DateTime(), nullable=False),
    sa.Column('status_shooping', sa.Enum('active', 'inactive', 'reserved', name='status_shooping_'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Shopping_Product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status_shopping', sa.Enum('active', 'inactive', 'completed', name='status_shopping_enum_'), nullable=False),
    sa.Column('created_at_shopping', sa.DateTime(), nullable=False),
    sa.Column('updated_at_shopping', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('status_paid', sa.Enum('paid', 'pending', 'refunded', name='status_paid_enum_'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('purchase_method', sa.String(), nullable=False),
    sa.Column('commission', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Shopping_Product')
    op.drop_table('Product')
    op.drop_table('User')
    # ### end Alembic commands ###
