"""empty message

Revision ID: 2efc68c10138
Revises: 4fff79ecb6f9
Create Date: 2023-01-29 16:11:23.469244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2efc68c10138'
down_revision = '4fff79ecb6f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopping_cart_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('paid', 'pending', 'refunded', name='bill_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['shopping_cart_id'], ['Shopping_Cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Bill')
    # ### end Alembic commands ###
