"""empty message

Revision ID: 40590468afd7
Revises: 01321acfdcee
Create Date: 2023-02-09 09:32:56.847525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40590468afd7'
down_revision = '01321acfdcee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
