"""empty message

Revision ID: 4dbab25a6785
Revises: a2957e91b6a6
Create Date: 2023-02-03 10:51:36.866724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbab25a6785'
down_revision = 'a2957e91b6a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'account_number',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=30, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'account_number',
               existing_type=sa.Numeric(precision=30, scale=0),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
