"""empty message

Revision ID: 7c31c523e8a0
Revises: 102e3a98c1e1
Create Date: 2023-02-03 14:17:19.582831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c31c523e8a0'
down_revision = '102e3a98c1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('User', sa.Column('name_first', sa.String(length=50), nullable=True))
    op.add_column('User', sa.Column('name_last', sa.String(length=50), nullable=True))
    op.add_column('User', sa.Column('location_street_number', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('location_street_name', sa.String(length=100), nullable=True))
    op.add_column('User', sa.Column('location_city', sa.String(length=50), nullable=True))
    op.add_column('User', sa.Column('location_state', sa.String(length=50), nullable=True))
    op.add_column('User', sa.Column('location_country', sa.String(length=50), nullable=True))
    op.add_column('User', sa.Column('location_postcode', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('location_timezone_offset', sa.String(length=10), nullable=True))
    op.add_column('User', sa.Column('location_timezone_description', sa.String(length=100), nullable=True))
    op.add_column('User', sa.Column('login_uuid', sa.String(length=100), nullable=True))
    op.add_column('User', sa.Column('login_username', sa.String(length=100), nullable=True))
    op.add_column('User', sa.Column('login_password', sa.String(length=100), nullable=True))
    op.add_column('User', sa.Column('dob_date', sa.String(length=100), nullable=True))
    op.add_column('User', sa.Column('dob_age', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('registered_date', sa.String(length=100), nullable=True))
    op.add_column('User', sa.Column('registered_age', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('User', sa.Column('cell', sa.String(length=20), nullable=True))
    op.add_column('User', sa.Column('picture_large', sa.String(length=200), nullable=True))
    op.add_column('User', sa.Column('picture_medium', sa.String(length=200), nullable=True))
    op.add_column('User', sa.Column('picture_thumbnail', sa.String(length=200), nullable=True))
    op.add_column('User', sa.Column('nat', sa.String(length=10), nullable=True))
    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
    op.drop_constraint('User_email_key', 'User', type_='unique')
    op.drop_constraint('User_paypal_key', 'User', type_='unique')
    op.drop_column('User', 'created_at_user')
    op.drop_column('User', 'is_admin')
    op.drop_column('User', 'account_prefix')
    op.drop_column('User', 'paypal')
    op.drop_column('User', 'password')
    op.drop_column('User', 'update_at_user')
    op.drop_column('User', 'user_profile_img')
    op.drop_column('User', 'account_number')
    op.drop_column('User', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('account_number', sa.NUMERIC(precision=30, scale=0), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('user_profile_img', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('update_at_user', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('paypal', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('account_prefix', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('created_at_user', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint('User_paypal_key', 'User', ['paypal'])
    op.create_unique_constraint('User_email_key', 'User', ['email'])
    op.alter_column('User', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('User', 'nat')
    op.drop_column('User', 'picture_thumbnail')
    op.drop_column('User', 'picture_medium')
    op.drop_column('User', 'picture_large')
    op.drop_column('User', 'cell')
    op.drop_column('User', 'phone')
    op.drop_column('User', 'registered_age')
    op.drop_column('User', 'registered_date')
    op.drop_column('User', 'dob_age')
    op.drop_column('User', 'dob_date')
    op.drop_column('User', 'login_password')
    op.drop_column('User', 'login_username')
    op.drop_column('User', 'login_uuid')
    op.drop_column('User', 'location_timezone_description')
    op.drop_column('User', 'location_timezone_offset')
    op.drop_column('User', 'location_postcode')
    op.drop_column('User', 'location_country')
    op.drop_column('User', 'location_state')
    op.drop_column('User', 'location_city')
    op.drop_column('User', 'location_street_name')
    op.drop_column('User', 'location_street_number')
    op.drop_column('User', 'name_last')
    op.drop_column('User', 'name_first')
    op.drop_column('User', 'gender')
    # ### end Alembic commands ###
