"""empty message

Revision ID: 9f5f45f3b929
Revises: 7c31c523e8a0
Create Date: 2023-02-03 14:56:52.296007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5f45f3b929'
down_revision = '7c31c523e8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.String(length=10), nullable=True))
    op.drop_column('User', 'name_first')
    op.drop_column('User', 'name_last')
    op.drop_column('User', 'location_timezone_offset')
    op.drop_column('User', 'registered_age')
    op.drop_column('User', 'cell')
    op.drop_column('User', 'login_password')
    op.drop_column('User', 'login_username')
    op.drop_column('User', 'location_timezone_description')
    op.drop_column('User', 'login_uuid')
    op.drop_column('User', 'nat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('nat', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('login_uuid', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('location_timezone_description', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('login_username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('login_password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('cell', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('registered_age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('location_timezone_offset', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('name_last', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('name_first', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('User', 'name')
    # ### end Alembic commands ###
