"""empty message

Revision ID: a2957e91b6a6
Revises: 1a3e1ac6d863
Create Date: 2023-02-03 10:44:12.696081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2957e91b6a6'
down_revision = '1a3e1ac6d863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('account_prefix', sa.String(length=10), nullable=False))
    op.alter_column('User', 'account_number',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'account_number',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('User', 'account_prefix')
    # ### end Alembic commands ###
