"""empty message

Revision ID: b76df507e3e1
Revises: 105c73310faa
Create Date: 2023-02-09 10:51:59.801487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b76df507e3e1'
down_revision = '105c73310faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('hash',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('hash',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               nullable=False)

    # ### end Alembic commands ###
