"""empty message

Revision ID: e3f55f1edc5f
Revises: 9f5f45f3b929
Create Date: 2023-02-03 15:10:28.698459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f55f1edc5f'
down_revision = '9f5f45f3b929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('account_prefix', sa.String(length=10), nullable=False))
    op.add_column('User', sa.Column('account_number', sa.Numeric(precision=30, scale=0), nullable=False))
    op.add_column('User', sa.Column('paypal', sa.String(length=255), nullable=False))
    op.add_column('User', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('User', sa.Column('login_username', sa.String(length=100), nullable=True))
    op.add_column('User', sa.Column('login_password', sa.String(length=100), nullable=True))
    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'User', ['paypal'])
    op.create_unique_constraint(None, 'User', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.alter_column('User', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('User', 'login_password')
    op.drop_column('User', 'login_username')
    op.drop_column('User', 'is_admin')
    op.drop_column('User', 'paypal')
    op.drop_column('User', 'account_number')
    op.drop_column('User', 'account_prefix')
    # ### end Alembic commands ###
