"""empty message

Revision ID: e7e373ac191e
Revises: 7fdf607ecb04
Create Date: 2023-02-08 16:27:53.284684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e373ac191e'
down_revision = '7fdf607ecb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('account_prefix',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('account_number',
               existing_type=sa.NUMERIC(precision=30, scale=0),
               nullable=True)
        batch_op.alter_column('paypal',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('paypal',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('account_number',
               existing_type=sa.NUMERIC(precision=30, scale=0),
               nullable=False)
        batch_op.alter_column('account_prefix',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
